services:
  rosbot:
    image: husarion/rosbot-xl:humble-0.10.0-20240216
    restart: unless-stopped
    ports:
      - 192.168.77.2:8888:8888/udp
    command: >
      ros2 launch /husarion_utils/rosbot.launch.py
        mecanum:=${MECANUM:-True}
        include_camera_mount:=True
        healthcheck:=False