x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  joy2twist:
    image: husarion/joy2twist:humble
    <<: *net-config
    devices:
      - /dev/input
    volumes: 
      - ./config/steamdeck.yaml:/params.yaml
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/params.yaml
