x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  rosbot-xl:
    image: husarion/rosbot-xl:humble
    <<: *net-config
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}

  microros:
    image: husarion/micro-ros-agent:humble
    <<: *net-config
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888
