services:
  joy2twist:
    image: husarion/joy2twist:humble
    restart: unless-stopped
    devices:
      - /dev/input
    volumes:
      - ./config/logitech-f710.yaml:/params.yaml
    command: >
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/params.yaml
